[pinecone]
api_key = "9eea2a51-a97d-4294-81cb-ec8bc4dd2cc0"
index_name = "spanos"
env_name = "us-east-1"


[openai]
api_key = "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"        