[pinecone]
api_key = "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"
index_name = "spanos"

[openai]
api_key = "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"